Honkai Star Rail.py
get_width.py
tool/calculated.py

自动获取width以及局部截图 

---

get_width.py

Reverts Starry-Wind/Honkai-Star-Rail#19

Revert "更新get_width"

---

Honkai Star Rail.py
get_width.py
tool/calculated.py

Reverts Starry-Wind/Honkai-Star-Rail#18

Revert "自动获取width以及局部截图 "

---

config.json
main.py
map_res_list.py
requirements.txt
test.py
tool/config.py
tool/log.py
tool/map.py
tool/update_file.py

1. 抓到了一些还在用标准json库的代码并换成了orjson
2. 新增webhook功能，在脚本开始和完成的时候将POST到config.json里的指定URL（默认关闭）
3. 把GitHub镜像站这个变量移到config.json里这样用户就可以自行指定镜像站（现在代码里写死的已经不能用了）

统一orjson，新增webhook，可设置的ghproxy变量

---

Honkai_Star_Rail.py
config.json
tool/calculated.py
tool/config.py
tool/log.py
tool/requests.py
tool/update_file.py

[添加一点注释](https://github.com/Starry-Wind/Honkai-Star-Rail/commit/80653e0fcd1b2b884d908c2ca4fa89e66aae0e14)
[添加pip install -r requirements.txt提示](https://github.com/Starry-Wind/Honkai-Star-Rail/commit/733e0fdab77543644c65287b379705c4d40ff2a8)

add: 添加一点注释

---

tool/config.py
tool/map.py

add: 添加打开地图配置项

---

Honkai_Star_Rail.py
tools/config.py
tools/log.py
tools/update_file.py

[fix: 修复因为json检验失败](https://github.com/Starry-Wind/Honkai-Star-Rail/commit/6f0fe0a7a74532d704b752dc585fac2938049ab0)
[add: 强制更新脚本](https://github.com/Starry-Wind/Honkai-Star-Rail/commit/00a4b7af26297dffd8b46edeb583a6519920b248)

fix: 修复因为json检验失败

---

Honkai_Star_Rail.py
tools/get_angle.py
tools/switch_window.py

获取人物朝向的函数暂未使用，为模拟宇宙造的轮子，当然跑图也能用得上

 更新自动切换窗口的功能，以及获取人物朝向的函数

---

tools/get_angle.py

- 在把函数名修改成 `get_furthest_point` 之后，没有修改对应的引用
- 删除了注释掉的代码

Fix: 修改函数名时，未修改相关引用

---

Honkai_Star_Rail.py

 在開啟時用os.system執行pip install -r requirements.txt

---

tools/update_file.py

Reverts Starry-Wind/Honkai-Star-Rail#191

Revert "fix: 将删除文件改成替换"

---

tools/calculated.py
tools/switch_window.py

Reverts Starry-Wind/Honkai-Star-Rail#210

Revert "fix: 繁體窗口辨識"

---

tools/calculated.py
tools/map.py

添加地图加载动画等待

---

Honkai_Star_Rail.py
tools/config.py
tools/map.py

feat: 添加地图选择器，无需输入地图编号

---

requirements.txt
tools/switch_window.py

Reverts Starry-Wind/Honkai-Star-Rail#235

Revert "fix: 使用win32gui激活窗口，hwnd检验"

---

utils/calculated.py
utils/map.py

入画时ui会消失, 所以可以通过检测团队图标, 来判断是否结束入画, 和战斗结束相似
fix #259 
- **测试**
``` {python} 
c = calculated()
c.teleport("f", 0.1)
c.move("s",.2)
```
预期: 人物入画能向后移动
结果: 符合预期

feat: 增加 入画检测

---

Honkai_Star_Rail.py
config.json
utils/adb.py
utils/calculated.py
utils/config.py
utils/cv_tools.py
utils/cv_tracker.py
utils/map.py

feat: 可指定adb可执行文件路径

---

Honkai_Star_Rail.py
utils/calculated.py
utils/log.py
utils/requests.py

chore: 部分点位重新启用ocr
fix: 修复地图打开异常

chore: 部分点位重新启用ocr，修复地图打开异常

---

utils/calculated.py

fix: 修复地图无限打开

---

Honkai_Star_Rail.py

之前结束脚本都是直接退了，重开脚本很浪费时间，把主菜单放到循环里面，退出脚本回到主菜单

add:添加返回主菜单操作

---

requirements.txt

修改依赖 flat -> flet

---

gui.py
utils/calculated.py
utils/config.py
utils/log.py
utils/map.py

chore: 进图识别优化
fix: 修复GUI无法正常加载新增菜单
fix: 修复国际化导致的报错

chore: 进图识别优化

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report_en.yml
utils/adb.py
utils/config.py

fix: 修复bud_report的错误配置

---

utils/calculated.py

chore: 加快进入地图等待时间

---

utils/calculated.py

在战斗状态时通过键盘按键 `v` 可以更改自动战斗设置，而无需使用鼠标定位点击。
通过按键替代坐标点击也更具鲁棒性。

refactor(utils/calculated): press v to auto battle

---

utils/calculated.py

Reverts Starry-Wind/StarRailAssistant#439

Revert "refactor(utils/calculated): press v to auto battle"

---

utils/calculated.py

Reverts Starry-Wind/StarRailAssistant#440

Revert "Revert "refactor(utils/calculated): press v to auto battle""

---

README.md
README_CHT.md
README_EN.md

- 关于「贡献」部分的说明，提醒提交至 `main-beta` 分支，防止再次出现 #439 的情况
- Markdown lint

docs(readme): contributions disc & markdown lint

---

README.md
README_CHT.md
README_EN.md
utils/calculated.py

[chore: 更新readme的py链接](https://github.com/Starry-Wind/StarRailAssistant/commit/b3180f62f0e6c48bc0041590a1823eab54264eba)

fix: 修复入画后角色不在移动

---

utils/calculated.py

perf: 优化calculated中函数的性能

---

utils/calculated.py

misc: 进一步优化

---

utils/map.py

feat: 添加漏怪统计功能

---

utils/calculated.py

优化改进攻击，补枪和反击代码

---

utils/config.py
utils/map.py

chore: 添加检漏开关(deficiency)

---

utils/calculated.py
utils/map.py

fix:修改错误的后缀名

---

utils/calculated.py
utils/map.py

chore:修改怪物检测机制,效果更好

---

utils/calculated.py
utils/map.py

chore: 代码优化和时间调整  添加漏怪截图

---

utils/calculated.py
utils/cv_tools.py

chore: 重写fighting函数

---

utils/calculated.py

修复一个多屏机器抓取屏幕图像的时候的时候会抓到全黑图像的问题

fix: take screenshot on multiscreen

---

README.md

fix: project name
